defmodule Repo.Migrations.AddNetsuiteCustomerTable do
  use Ecto.Migration

  def up do
    create table("netsuite_customers") do
      add :alcoholrecipienttype, :text
      add :altname, :text
      add :altphone, :text
      add :balancesearch, :text
      add :category, :text
      add :companyname, :text
      add :consolbalancesearch, :text
      add :consoldaysoverduesearch, :text
      add :consoloverduebalancesearch, :text
      add :consolunbilledorderssearch, :text
      add :creditholdoverride, :text
      add :currency, :text
      add :custentity2, :text
      add :custentity_bb_entity_latitude_text, :text
      add :custentity_bb_entity_longitude_text, :text
      add :custentity_bb_fin_install_per_watt_amt, :text
      add :custentity_bb_fin_orig_base_per_watt_amt, :text
      add :custentity_bb_fin_prelim_purch_price_amt, :text
      add :custentity_bb_financier_customer, :text
      add :custentity_bb_financier_payment_schedule, :text
      add :custentity_bb_financing_type, :text
      add :custentity_bb_home_owner_name_text, :text
      add :custentity_bb_home_owner_phone, :text
      add :custentity_bb_home_owner_primary_email, :text
      add :custentity_bb_homeowner_association, :text
      add :custentity_bb_install_address_1_text, :text
      add :custentity_bb_install_address_2_text, :text
      add :custentity_bb_install_city_text, :text
      add :custentity_bb_install_state, :text
      add :custentity_bb_install_zip_code_text, :text
      add :custentity_bb_inverter_quantity_num, :text
      add :custentity_bb_is_address_rec_boolean, :text
      add :custentity_bb_lead_start_date, :text
      add :custentity_bb_module_quantity_num, :text
      add :custentity_bb_ob_project_uuid, :text
      add :custentity_bb_project, :text
      add :custentity_bb_spouse_name, :text
      add :custentity_bb_started_from_proj_template, :text
      add :custentity_bb_system_size_decimal, :text
      add :custentity_bb_utility_company, :text
      add :custentity_bb_warehouse_location, :text
      add :custentity_bbss_configuration, :text
      add :custentity_bluchat_full_mention_list, :text
      add :custentity_sk_array_type, :text
      add :custentity_sk_battery_model, :text
      add :custentity_sk_cash_back, :text
      add :custentity_sk_closing_customer_notes, :text
      add :custentity_sk_critter_guard, :text
      add :custentity_sk_derate_breaker, :text
      add :custentity_sk_ev_charger, :text
      add :custentity_sk_extended_invertery_warrant, :text
      add :custentity_sk_extended_product, :text
      add :custentity_sk_finance_term_length, :text
      add :custentity_sk_hoi_received, :text
      add :custentity_sk_interest_rate, :text
      add :custentity_sk_inverter_model, :text
      add :custentity_sk_led, :text
      add :custentity_sk_main_panel_upgrade, :text
      add :custentity_sk_meter_combine, :text
      add :custentity_sk_meter_upgrade, :text
      add :custentity_sk_module_model, :text
      add :custentity_sk_module_size, :text
      add :custentity_sk_number_of_arrays, :text
      add :custentity_sk_panel_skirts, :text
      add :custentity_sk_premium_panels, :text
      add :custentity_sk_proposal_link, :text
      add :custentity_sk_roof_pitch, :text
      add :custentity_sk_roof_reinforcement, :text
      add :custentity_sk_roof_repairs, :text
      add :custentity_sk_site_survey_date, :text
      add :custentity_sk_smart_thermostat, :text
      add :custentity_sk_tree_trimming, :text
      add :custentity_sk_trenching_ground_type, :text
      add :custentity_sk_trenching_length, :text
      add :custentity_sk_upsized_inverter, :text
      add :custentity_sk_utility_account_name, :text
      add :custentity_sk_utility_account_number, :text
      add :custentity_sk_xcel_premise_number, :text
      add :custentity_sk_sales_rep, :text
      add :custentity_skl_hs_dealid, :bigint
      add :custentity_skl_hubspot_id, :bigint
      add :custentity_ss_customer_class, :text
      add :custentitysk_firstprojectcreated, :text
      add :datecreated, :text
      add :defaultbillingaddress, :text
      add :defaultshippingaddress, :text
      add :displaysymbol, :text
      add :duplicate, :text
      add :email, :text
      add :emailpreference, :text
      add :emailtransactions, :text
      add :entityid, :text
      add :entitynumber, :text
      add :entitystatus, :text
      add :entitytitle, :text
      add :faxtransactions, :text
      add :firstname, :text
      add :firstorderdate, :text
      add :firstsaledate, :text
      add :giveaccess, :text
      add :netsuite_customer_id, :bigint
      add :isbudgetapproved, :text
      add :isinactive, :text
      add :isperson, :text
      add :lastmodifieddate, :text
      add :lastname, :text
      add :lastorderdate, :text
      add :lastsaledate, :text
      add :leadsource, :text
      add :links, {:array, :text}
      add :middlename, :text
      add :mobilephone, :text
      add :oncredithold, :text
      add :overduebalancesearch, :text
      add :overridecurrencyformat, :text
      add :parent, :text
      add :phone, :text
      add :printoncheckas, :text
      add :printtransactions, :text
      add :probability, :text
      add :receivablesaccount, :text
      add :searchstage, :text
      add :shipcomplete, :text
      add :shippingcarrier, :text
      add :startdate, :text
      add :symbolplacement, :text
      add :unbilledorderssearch, :text
      add :weblead, :text
      add :custentity_skl_sales_adders, :text
      add :custentity_skl_sales_promises, :text
      add :custentity_skl_hs_hoa_note, :text
      timestamps()
    end

    create unique_index(:netsuite_customers, [:netsuite_customer_id])
  end

  def down do
    drop table("netsuite_customers")
  end
end
