defmodule Repo.Migrations.AddNetsuiteProjectTable do
  use Ecto.Migration

  def up do
    create table("netsuite_projects") do
      add :netsuite_project_id, :bigint
      add :actualtime, :text
      add :allowallresourcesfortasks, :text
      add :allowexpenses, :text
      add :allowtime, :text
      add :altname, :text
      add :calculatedenddate, :text
      add :comments, :text
      add :companyname, :text
      add :cseg_bb_project, :text
      add :customer, :text
      add :datecreated, :text
      add :entityid, :text
      add :entitynumber, :text
      add :entitytitle, :text
      add :estimatedgrossprofit, :text
      add :estimatedlaborcost, :text
      add :estimatedlaborrevenue, :text
      add :estimatedtime, :text
      add :estimatedtimeoverride, :text
      add :files, :text
      add :includecrmtasksintotals, :text
      add :isexempttime, :text
      add :isinactive, :text
      add :isproductivetime, :text
      add :isutilizedtime, :text
      add :lastmodifieddate, :text
      add :limittimetoassignees, :text
      add :links, {:array, :text}
      add :materializetime, :text
      add :parent, :text
      add :percenttimecomplete, :text
      add :startdate, :text
      add :timeapproval, :text
      add :timeremaining, :text
      # custentity stuff below
      add :custentity_bb_on_hold_reason, :text
      add :custentitysk_update_hubspot_deal, :text
      add :custentitybb_change_of_scope_comments, :text
      add :custentity2, :text
      add :custentity_ss_customer_class, :text
      add :custentity_skyline_bludoc_create, :text
      add :custentity_skl_hubspot_id, :bigint
      add :custentity_skl_hs_updatedidtodeal, :text
      add :custentity_skl_hs_dealid, :bigint
      add :custentity_skl_currentmilestone, :text
      add :custentity_sk_xcel_premise_number, :text
      add :custentity_sk_utility_account_number, :text
      add :custentity_sk_utility_account_name, :text
      add :custentity_sk_upsized_inverter, :text
      add :custentity_sk_trenching_length, :text
      add :custentity_sk_trenching_ground_type, :text
      add :custentity_sk_tree_trimming, :text
      add :custentity_sk_smart_thermostat, :text
      add :custentity_sk_site_survey_date, :text
      add :custentity_sk_second_inverter_model, :text
      add :custentity_sk_sales_rep, :text
      add :custentity_sk_roof_repairs, :text
      add :custentity_sk_roof_reinforcement, :text
      add :custentity_sk_roof_pitch, :text
      add :custentity_sk_referred_by, :text
      add :custentity_sk_proposal_link, :text
      add :custentity_sk_primary_language, :text
      add :custentity_sk_premium_panels, :text
      add :custentity_sk_permit_number, :text
      add :custentity_sk_panel_skirts, :text
      add :custentity_sk_number_of_arrays, :text
      add :custentity_sk_nps_score, :text
      add :custentity_sk_nma_number, :text
      add :custentity_sk_module_size, :text
      add :custentity_sk_module_model, :text
      add :custentity_sk_meter_upgrade, :text
      add :custentity_sk_meter_combine, :text
      add :custentity_sk_main_panel_upgrade, :text
      add :custentity_sk_led, :text
      add :custentity_sk_inverter_model, :text
      add :custentity_sk_interest_rate, :text
      add :custentity_sk_hoi_received, :text
      add :custentity_sk_finance_term_length, :text
      add :custentity_sk_extended_product, :text
      add :custentity_sk_extended_invertery_warrant, :text
      add :custentity_sk_ev_charger, :text
      add :custentity_sk_derate_breaker, :text
      add :custentity_sk_critter_guard, :text
      add :custentity_sk_closing_customer_notes, :text
      add :custentity_sk_cash_back, :text
      add :custentity_sk_battery_model, :text
      add :custentity_sk_array_type, :text
      add :custentity_inv_enrg_consmptn_src_lst, :text
      add :custentity_bludocs_gdrive_viewer, :text
      add :custentity_bbss_configuration, :text
      add :custentity_bb_zoning_text, :text
      add :custentity_bb_wrnty_pay_comments_text, :text
      add :custentity_bb_wrnty_expiration_date, :text
      add :custentity_bb_warranty_service_amount, :text
      add :custentity_bb_warranty_reserve_amount, :text
      add :custentity_bb_warranty_inventory_amount, :text
      add :custentity_bb_warranty_comments_text, :text
      add :custentity_bb_utility_zone, :text
      add :custentity_bb_utility_rate_schedule, :text
      add :custentity_bb_utility_monthly_avg_dec, :text
      add :custentity_bb_utility_company, :text
      add :custentity_bb_uses_proj_actn_tran_schdl, :text
      add :custentity_bb_tran_comments_text, :text
      add :custentity_bb_total_project_ar_amount, :text
      add :custentity_bb_total_dealer_fee_amount, :text
      add :custentity_bb_total_contract_value_amt, :text
      add :custentity_bb_tot_contract_value_cpy_amt, :text
      add :custentity_bb_tot_con_value_per_watt_amt, :text
      add :custentity_bb_timezone, :text
      add :custentity_bb_tilt_degrees_num, :text
      add :custentity_bb_system_size_decimal, :text
      add :custentity_bb_subst_compl_status_txt, :text
      add :custentity_bb_subst_compl_pack_start_dt, :text
      add :custentity_bb_subst_compl_pack_end_dt, :text
      add :custentity_bb_subst_compl_pack_dur_num, :text
      add :custentity_bb_subst_compl_pack_comments, :text
      add :custentity_bb_subst_compl_pack_comm_hist, :text
      add :custentity_bb_subst_compl_last_mod_dt, :text
      add :custentity_bb_subinstl_vend_credit_total, :text
      add :custentity_bb_subinstl_vend_bill_total, :text
      add :custentity_bb_struct_const_mat_type, :text
      add :custentity_bb_stories_num, :text
      add :custentity_bb_started_from_proj_template, :text
      add :custentity_bb_ss_solaredge_site_id, :text
      add :custentity_bb_ss_sales_tax_account, :text
      add :custentity_bb_ss_powerfactors_site_id, :text
      add :custentity_bb_ss_org_already_billed_amt, :text
      add :custentity_bb_ss_invoice_day, :text
      add :custentity_bb_ss_inst_already_billed_amt, :text
      add :custentity_bb_ss_alsoenergy_site_id, :text
      add :custentity_bb_ss_already_invoiced_amount, :text
      add :custentity_bb_ss_all_pa_files, :text
      add :custentity_bb_ss_accrual_journal, :text
      add :custentity_bb_sq_foot_num, :text
      add :custentity_bb_spouse_name, :text
      add :custentity_bb_solar_portion_contract_amt, :text
      add :custentity_bb_snap_shot_pay_roll_period, :text
      add :custentity_bb_site_audit_vendor, :text
      add :custentity_bb_site_audit_scheduled_date, :text
      add :custentity_bb_site_audit_payment_comment, :text
      add :custentity_bb_site_audit_pack_status_txt, :text
      add :custentity_bb_site_audit_pack_start_date, :text
      add :custentity_bb_site_audit_pack_last_date, :text
      add :custentity_bb_site_audit_pack_end_date, :text
      add :custentity_bb_site_audit_pack_dur_num, :text
      add :custentity_bb_site_audit_pack_comments, :text
      add :custentity_bb_site_audit_pack_comm_hist, :text
      add :custentity_bb_site_audit_contact_email, :text
      add :custentity_bb_site_audit_amount, :text
      add :custentity_bb_shipping_amount, :text
      add :custentity_bb_ship_zip_text, :text
      add :custentity_bb_ship_state, :text
      add :custentity_bb_ship_city_text, :text
      add :custentity_bb_ship_address_2_text, :text
      add :custentity_bb_ship_address_1_text, :text
      add :custentity_bb_services_costs_pr_watt_amt, :text
      add :custentity_bb_services_costs_amount, :text
      add :custentity_bb_sep_kwh_integer, :text
      add :custentity_bb_second_inverter_qty_num, :text
      add :custentity_bb_second_inverter_item, :text
      add :custentity_bb_second_inverter_desc_text, :text
      add :custentity_bb_sales_tax_amount, :text
      add :custentity_bb_sales_rep_employee, :text
      add :custentity_bb_sales_rep_email, :text
      add :custentity_bb_sales_rep_comm_amt, :text
      add :custentity_bb_sales_rep_comm_amt_overrid, :text
      add :custentity_bb_sales_partner_pay_schedule, :text
      add :custentity_bb_sales_cost_p_watt_amount, :text
      add :custentity_bb_sales_cost_amount, :text
      add :custentity_bb_roof_type, :text
      add :custentity_bb_roof_structure_type, :text
      add :custentity_bb_roof_material_type, :text
      add :custentity_bb_rma_comments_text, :text
      add :custentity_bb_rma_amount, :text
      add :custentity_bb_revenue_per_watt_amount, :text
      add :custentity_bb_revenue_amount, :text
      add :custentity_bb_requires_hoa_application, :text
      add :custentity_bb_require_call_ahead, :text
      add :custentity_bb_requested_delivery_date, :text
      add :custentity_bb_recent_seller_text, :text
      add :custentity_bb_recent_buyer_text, :text
      add :custentity_bb_rebate_variance_amount, :text
      add :custentity_bb_rebate_package_status_text, :text
      add :custentity_bb_rebate_package_start_date, :text
      add :custentity_bb_rebate_package_last_mod_dt, :text
      add :custentity_bb_rebate_package_end_date, :text
      add :custentity_bb_rebate_package_comments, :text
      add :custentity_bb_rebate_pack_duration_num, :text
      add :custentity_bb_rebate_pack_comm_history, :text
      add :custentity_bb_rebate_included_yes_no, :text
      add :custentity_bb_rebate_customer, :text
      add :custentity_bb_rebate_confirmation_amount, :text
      add :custentity_bb_rebate_conf_amount_copy, :text
      add :custentity_bb_rebate_assignee, :text
      add :custentity_bb_rebate_assignee_copy_text, :text
      add :custentity_bb_rebate_application_amount, :text
      add :custentity_bb_rebate_app_amount_copy, :text
      add :custentity_bb_pv_production_meter_url, :text
      add :custentity_bb_pv_production_meter_item, :text
      add :custentity_bb_pv_prod_meter_id_text, :text
      add :custentity_bb_proposal_generated_date, :text
      add :custentity_bb_property_feet_decimal, :text
      add :custentity_bb_prop_type, :text
      add :custentity_bb_project_sub_stage_text, :text
      add :custentity_bb_project_status, :text
      add :custentity_bb_project_start_date, :text
      add :custentity_bb_project_stage_text, :text
      add :custentity_bb_project_so, :text
      add :custentity_bb_project_serial_number_text, :text
      add :custentity_bb_project_program_type, :text
      add :custentity_bb_project_partner, :text
      add :custentity_bb_project_manager_employee, :text
      add :custentity_bb_project_location, :text
      add :custentity_bb_project_acctg_method, :text
      add :custentity_bb_proj_install_type, :text
      add :custentity_bb_proj_install_dates_html, :text
      add :custentity_bb_proj_inspection_dates_html, :text
      add :custentity_bb_proj_inc_stmnt, :text
      add :custentity_bb_proj_home_type, :text
      add :custentity_bb_proj_google_maps_zoom, :text
      add :custentity_bb_proj_fin_accpt_dates_html, :text
      add :custentity_bb_proj_design_dates_html, :text
      add :custentity_bb_proj_dates_html, :text
      add :custentity_bb_proj_cac_dates_html, :text
      add :custentity_bb_proj_bal_sheet, :text
      add :custentity_bb_proj_address_text, :text
      add :custentity_bb_price_per_kwh_amount, :text
      add :custentity_bb_prefers_site_audit_as_addr, :text
      add :custentity_bb_prefers_design_amt_as_addr, :text
      add :custentity_bb_pay_on_hold_user, :text
      add :custentity_bb_paid_comm_amount, :text
      add :custentity_bb_owner_verification_text, :text
      add :custentity_bb_originator_vendor, :text
      add :custentity_bb_originator_pymt_memo_html, :text
      add :custentity_bb_originator_per_watt_amt, :text
      add :custentity_bb_originator_pay_memo_html, :text
      add :custentity_bb_originator_email, :text
      add :custentity_bb_originator_base_p_watt_amt, :text
      add :custentity_bb_originator_base_amt, :text
      add :custentity_bb_orig_vend_credit_total, :text
      add :custentity_bb_orig_vend_bill_total, :text
      add :custentity_bb_orig_tot_vendor_bill_amt, :text
      add :custentity_bb_orig_payout_total, :text
      add :custentity_bb_orig_payments_on_hold_bool, :text
      add :custentity_bb_orig_payment_on_hold_date, :text
      add :custentity_bb_orig_pay_total_overide_amt, :text
      add :custentity_bb_orig_override_user, :text
      add :custentity_bb_orig_override_date, :text
      add :custentity_bb_orig_override_boolean, :text
      add :custentity_bb_orgntr_per_watt_adder_amt, :text
      add :custentity_bb_orgntr_per_mod_adder_amt, :text
      add :custentity_bb_orgntr_per_ft_addr_ttl_amt, :text
      add :custentity_bb_orgntr_payment_tot_amt, :text
      add :custentity_bb_orgntr_pay_tot_p_w_amt, :text
      add :custentity_bb_orgntr_m7_vbill_perc, :text
      add :custentity_bb_orgntr_m7_vbill_amt, :text
      add :custentity_bb_orgntr_m6_vbill_perc, :text
      add :custentity_bb_orgntr_m6_vbill_amt, :text
      add :custentity_bb_orgntr_m5_vbill_perc, :text
      add :custentity_bb_orgntr_m5_vbill_amt, :text
      add :custentity_bb_orgntr_m4_vbill_perc, :text
      add :custentity_bb_orgntr_m4_vbill_amt, :text
      add :custentity_bb_orgntr_m3_vbill_perc, :text
      add :custentity_bb_orgntr_m3_vbill_amt, :text
      add :custentity_bb_orgntr_m2_vbill_perc, :text
      add :custentity_bb_orgntr_m2_vbill_amt, :text
      add :custentity_bb_orgntr_m1_vbill_perc, :text
      add :custentity_bb_orgntr_m1_vbill_amt, :text
      add :custentity_bb_orgntr_m0_vbill_perc, :text
      add :custentity_bb_orgntr_m0_vbill_amt, :text
      add :custentity_bb_orgntr_fxd_addr_ttl_amt, :text
      add :custentity_bb_orgntr_addr_ttl_p_watt_amt, :text
      add :custentity_bb_orgntr_addr_ttl_amt, :text
      add :custentity_bb_oct_kwh_integer, :text
      add :custentity_bb_ob_project_uuid, :text
      add :custentity_bb_nov_kwh_integer, :text
      add :custentity_bb_net_price_per_watt, :text
      add :custentity_bb_mounting_type, :text
      add :custentity_bb_months_in_contract_num, :text
      add :custentity_bb_module_quantity_num, :text
      add :custentity_bb_module_item, :text
      add :custentity_bb_module_install_doc, :text
      add :custentity_bb_module_description_text, :text
      add :custentity_bb_middle_name, :text
      add :custentity_bb_medeek_snow_load, :text
      add :custentity_bb_medeek_716_wind_risk_i, :text
      add :custentity_bb_may_kwh_integer, :text
      add :custentity_bb_marketing_campaign, :text
      add :custentity_bb_market_value_num, :text
      add :custentity_bb_market_segment, :text
      add :custentity_bb_mar_kwh_integer, :text
      add :custentity_bb_manual_paid_comm_amount, :text
      add :custentity_bb_m7_sub_install_date, :text
      add :custentity_bb_m7_sub_install_action, :text
      add :custentity_bb_m7_origination_date, :text
      add :custentity_bb_m7_origination_action, :text
      add :custentity_bb_m7_finance_action, :text
      add :custentity_bb_m7_dealer_fee_amount, :text
      add :custentity_bb_m7_date, :text
      add :custentity_bb_m6_sub_install_date, :text
      add :custentity_bb_m6_sub_install_action, :text
      add :custentity_bb_m6_origination_date, :text
      add :custentity_bb_m6_origination_action, :text
      add :custentity_bb_m6_finance_action, :text
      add :custentity_bb_m6_dealer_fee_amount, :text
      add :custentity_bb_m6_date, :text
      add :custentity_bb_m5_sub_install_date, :text
      add :custentity_bb_m5_sub_install_action, :text
      add :custentity_bb_m5_origination_date, :text
      add :custentity_bb_m5_origination_action, :text
      add :custentity_bb_m5_finance_action, :text
      add :custentity_bb_m5_dealer_fee_amount, :text
      add :custentity_bb_m5_date, :text
      add :custentity_bb_m4_sub_install_date, :text
      add :custentity_bb_m4_sub_install_action, :text
      add :custentity_bb_m4_origination_date, :text
      add :custentity_bb_m4_origination_action, :text
      add :custentity_bb_m4_finance_action, :text
      add :custentity_bb_m4_dealer_fee_amount, :text
      add :custentity_bb_m4_date, :text
      add :custentity_bb_m3_sub_install_date, :text
      add :custentity_bb_m3_sub_install_action, :text
      add :custentity_bb_m3_origination_date, :text
      add :custentity_bb_m3_origination_action, :text
      add :custentity_bb_m3_finance_action, :text
      add :custentity_bb_m3_dealer_fee_amount, :text
      add :custentity_bb_m3_date, :text
      add :custentity_bb_m2_sub_install_date, :text
      add :custentity_bb_m2_sub_install_action, :text
      add :custentity_bb_m2_origination_date, :text
      add :custentity_bb_m2_origination_action, :text
      add :custentity_bb_m2_finance_action, :text
      add :custentity_bb_m2_dealer_fee_amount, :text
      add :custentity_bb_m2_date, :text
      add :custentity_bb_m1_sub_install_date, :text
      add :custentity_bb_m1_sub_install_action, :text
      add :custentity_bb_m1_origination_date, :text
      add :custentity_bb_m1_origination_action, :text
      add :custentity_bb_m1_finance_action, :text
      add :custentity_bb_m1_dealer_fee_amount, :text
      add :custentity_bb_m1_date, :text
      add :custentity_bb_m0_sub_install_date, :text
      add :custentity_bb_m0_sub_install_action, :text
      add :custentity_bb_m0_origination_date, :text
      add :custentity_bb_m0_origination_action, :text
      add :custentity_bb_m0_finance_action, :text
      add :custentity_bb_m0_dealer_fee_amount, :text
      add :custentity_bb_m0_date, :text
      add :custentity_bb_lot_size_num, :text
      add :custentity_bb_loan_id_text, :text
      add :custentity_bb_lead_vendor, :text
      add :custentity_bb_lead_start_date, :text
      add :custentity_bb_last_name, :text
      add :custentity_bb_jun_kwh_integer, :text
      add :custentity_bb_jul_kwh_integer, :text
      add :custentity_bb_jan_kwh_integer, :text
      add :custentity_bb_is_vendor_owned_inverter, :text
      add :custentity_bb_is_residential_delivery, :text
      add :custentity_bb_is_project_template, :text
      add :custentity_bb_is_occupied, :text
      add :custentity_bb_inverter_quantity_num, :text
      add :custentity_bb_inverter_item, :text
      add :custentity_bb_inverter_description_text, :text
      add :custentity_bb_inverter_comments_text, :text
      add :custentity_bb_inventory_amount, :text
      add :custentity_bb_instllr_pr_wt_addr_ttl_amt, :text
      add :custentity_bb_instllr_pr_md_addr_ttl_amt, :text
      add :custentity_bb_installr_p_ft_addr_ttl_amt, :text
      add :custentity_bb_installer_vbill_ttl_amt, :text
      add :custentity_bb_installer_total_pay_amt, :text
      add :custentity_bb_installer_price_p_w, :text
      add :custentity_bb_installer_pay_memo_html, :text
      add :custentity_bb_installer_partner_vendor, :text
      add :custentity_bb_installer_main_conct_email, :text
      add :custentity_bb_installer_m7_vbill_perc, :text
      add :custentity_bb_installer_m7_vbill_amt, :text
      add :custentity_bb_installer_m6_vbill_perc, :text
      add :custentity_bb_installer_m6_vbill_amt, :text
      add :custentity_bb_installer_m5_vbill_perc, :text
      add :custentity_bb_installer_m5_vbill_amt, :text
      add :custentity_bb_installer_m4_vbill_perc, :text
      add :custentity_bb_installer_m4_vbill_amt, :text
      add :custentity_bb_installer_m3_vbill_perc, :text
      add :custentity_bb_installer_m3_vbill_amt, :text
      add :custentity_bb_installer_m2_vbill_perc, :text
      add :custentity_bb_installer_m2_vbill_amt, :text
      add :custentity_bb_installer_m1_vbill_perc, :text
      add :custentity_bb_installer_m1_vbill_amt, :text
      add :custentity_bb_installer_m0_vbill_perc, :text
      add :custentity_bb_installer_m0_vbill_amt, :text
      add :custentity_bb_installer_fxd_addr_ttl_amt, :text
      add :custentity_bb_installer_amt, :text
      add :custentity_bb_installer_adder_total_amt, :text
      add :custentity_bb_install_zip_code_text, :text
      add :custentity_bb_install_total_payment_p_w, :text
      add :custentity_bb_install_state, :text
      add :custentity_bb_install_scheduled_date, :text
      add :custentity_bb_install_payout_total, :text
      add :custentity_bb_install_pay_total_ovrd_amt, :text
      add :custentity_bb_install_part_pay_schedule, :text
      add :custentity_bb_install_comp_pack_stat_txt, :text
      add :custentity_bb_install_comp_pack_start_dt, :text
      add :custentity_bb_install_comp_pack_last_dt, :text
      add :custentity_bb_install_comp_pack_end_date, :text
      add :custentity_bb_install_comp_pack_dur_num, :text
      add :custentity_bb_install_comp_pack_date, :text
      add :custentity_bb_install_comp_pack_comments, :text
      add :custentity_bb_install_comp_pack_comm_his, :text
      add :custentity_bb_install_comp_deadline_date, :text
      add :custentity_bb_install_city_text, :text
      add :custentity_bb_install_address_2_text, :text
      add :custentity_bb_install_address_1_text, :text
      add :custentity_bb_install_adder_tot_p_w_amt, :text
      add :custentity_bb_inspection_partner_vendor, :text
      add :custentity_bb_inspection_main_cont_email, :text
      add :custentity_bb_inspection_amount, :text
      add :custentity_bb_inspect_pay_comments_text, :text
      add :custentity_bb_homeowner_finance_method, :text
      add :custentity_bb_homeowner_customer, :text
      add :custentity_bb_homeowner_association, :text
      add :custentity_bb_home_owner_primary_email, :text
      add :custentity_bb_home_owner_phone, :text
      add :custentity_bb_home_owner_name_text, :text
      add :custentity_bb_home_owner_alt_email, :text
      add :custentity_bb_hoa_zip_text, :text
      add :custentity_bb_hoa_turn_around, :text
      add :custentity_bb_hoa_review_time_text, :text
      add :custentity_bb_hoa_phone, :text
      add :custentity_bb_hoa_package_status_text, :text
      add :custentity_bb_hoa_package_start_date, :text
      add :custentity_bb_hoa_package_last_mod_date, :text
      add :custentity_bb_hoa_package_end_date, :text
      add :custentity_bb_hoa_package_comments, :text
      add :custentity_bb_hoa_package_comm_history, :text
      add :custentity_bb_hoa_pack_duration_num, :text
      add :custentity_bb_hoa_name_text, :text
      add :custentity_bb_hoa_email, :text
      add :custentity_bb_hoa_deposit_status_text, :text
      add :custentity_bb_ho_credit_approval_date, :text
      add :custentity_bb_ho_contacted_site_audit_dt, :text
      add :custentity_bb_has_lift_gate, :text
      add :custentity_bb_gross_trading_profit_amt, :text
      add :custentity_bb_gross_profit_percent, :text
      add :custentity_bb_gross_profit_amount, :text
      add :custentity_bb_gross_adder_total, :text
      add :custentity_bb_google_maps_api_key, :text
      add :custentity_bb_gen_rebate_on_milestone, :text
      add :custentity_bb_foundation_type, :text
      add :custentity_bb_forecasted_install_date, :text
      add :custentity_bb_forecasted_close_date, :text
      add :custentity_bb_forecast_type, :text
      add :custentity_bb_forecast_site_survey_date, :text
      add :custentity_bb_forecast_pto_date, :text
      add :custentity_bb_forecast_permit_date, :text
      add :custentity_bb_forecast_inspection_date, :text
      add :custentity_bb_forecast_design_date, :text
      add :custentity_bb_first_name, :text
      add :custentity_bb_fincancer_email, :text
      add :custentity_bb_financing_type, :text
      add :custentity_bb_financier_stips_comment, :text
      add :custentity_bb_financier_payment_schedule, :text
      add :custentity_bb_financier_loan_url, :text
      add :custentity_bb_financier_customer, :text
      add :custentity_bb_financier_adv_pmt_schedule, :text
      add :custentity_bb_final_completion_date, :text
      add :custentity_bb_final_acc_pack_status_text, :text
      add :custentity_bb_final_acc_pack_start_date, :text
      add :custentity_bb_final_acc_pack_last_mod_dt, :text
      add :custentity_bb_final_acc_pack_end_date, :text
      add :custentity_bb_final_acc_pack_comments, :text
      add :custentity_bb_final_acc_pack_com_history, :text
      add :custentity_bb_fin_total_invoice_amount, :text
      add :custentity_bb_fin_total_fees_amount, :text
      add :custentity_bb_fin_rebate_inv_amount, :text
      add :custentity_bb_fin_pur_price_p_watt_amt, :text
      add :custentity_bb_fin_proposal_id_text, :text
      add :custentity_bb_fin_prelim_purch_price_amt, :text
      add :custentity_bb_fin_per_watt_adder_amt, :text
      add :custentity_bb_fin_per_module_adder_amt, :text
      add :custentity_bb_fin_per_foot_adder_amt, :text
      add :custentity_bb_fin_payment_memo_html, :text
      add :custentity_bb_fin_owned_equip_costs_amt, :text
      add :custentity_bb_fin_orig_per_watt_amt, :text
      add :custentity_bb_fin_orig_base_per_watt_amt, :text
      add :custentity_bb_fin_orig_base_amt, :text
      add :custentity_bb_fin_monitoring_fee_amount, :text
      add :custentity_bb_fin_m7_invoice_percent, :text
      add :custentity_bb_fin_m7_invoice_amount, :text
      add :custentity_bb_fin_m6_invoice_percent, :text
      add :custentity_bb_fin_m6_invoice_amount, :text
      add :custentity_bb_fin_m5_invoice_percent, :text
      add :custentity_bb_fin_m5_invoice_amount, :text
      add :custentity_bb_fin_m4_invoice_percent, :text
      add :custentity_bb_fin_m4_invoice_amount, :text
      add :custentity_bb_fin_m3_invoice_percent, :text
      add :custentity_bb_fin_m3_invoice_amount, :text
      add :custentity_bb_fin_m2_invoice_percent, :text
      add :custentity_bb_fin_m2_invoice_amount, :text
      add :custentity_bb_fin_m1_invoice_percent, :text
      add :custentity_bb_fin_m1_invoice_amount, :text
      add :custentity_bb_fin_m0_invoice_percent, :text
      add :custentity_bb_fin_m0_invoice_amount, :text
      add :custentity_bb_fin_install_per_watt_amt, :text
      add :custentity_bb_fin_install_base_amt, :text
      add :custentity_bb_fin_fixed_adder_amt, :text
      add :custentity_bb_fin_customer_id_text, :text
      add :custentity_bb_fin_base_fees_amount, :text
      add :custentity_bb_feb_kwh_integer, :text
      add :custentity_bb_fa_pack_duration_num, :text
      add :custentity_bb_estimated_annual_kwh_dec, :text
      add :custentity_bb_est_annual_savings_amt, :text
      add :custentity_bb_equipment_disposition, :text
      add :custentity_bb_equip_tran_comments_text, :text
      add :custentity_bb_equip_shipping_apprvl_date, :text
      add :custentity_bb_equip_shipping_approval, :text
      add :custentity_bb_equip_ship_contact_txt, :text
      add :custentity_bb_equip_cost_per_watt_amount, :text
      add :custentity_bb_equip_cost_amount, :text
      add :custentity_bb_epc_role, :text
      add :custentity_bb_entity_property_link, :text
      add :custentity_bb_entity_property_image, :text
      add :custentity_bb_entity_longitude_text, :text
      add :custentity_bb_entity_latitude_text, :text
      add :custentity_bb_energy_rate_type, :text
      add :custentity_bb_energy_rate_schedule, :text
      add :custentity_bb_energy_production_source, :text
      add :custentity_bb_down_payment_all_milestone, :text
      add :custentity_bb_difference_approver, :text
      add :custentity_bb_difference_approved_date, :text
      add :custentity_bb_design_payment_comments, :text
      add :custentity_bb_design_partner_vendor, :text
      add :custentity_bb_design_package_start_date, :text
      add :custentity_bb_design_package_end_date, :text
      add :custentity_bb_design_package_comments, :text
      add :custentity_bb_design_pack_status_text, :text
      add :custentity_bb_design_pack_last_mod_date, :text
      add :custentity_bb_design_pack_duration_num, :text
      add :custentity_bb_design_pack_comm_history, :text
      add :custentity_bb_design_main_contact_email, :text
      add :custentity_bb_design_amount, :text
      add :custentity_bb_dedct_rebate_all_milestone, :text
      add :custentity_bb_dec_kwh_integer, :text
      add :custentity_bb_dealer_fee_percent, :text
      add :custentity_bb_dealer_fee_app_method, :text
      add :custentity_bb_datatree_hoa_name_text, :text
      add :custentity_bb_customer_signture_date, :text
      add :custentity_bb_customer_category, :text
      add :custentity_bb_cust_record_link, :text
      add :custentity_bb_credit_initiated_date, :text
      add :custentity_bb_copy_to, :text
      add :custentity_bb_copy_from, :text
      add :custentity_bb_contract_value_hist_html, :text
      add :custentity_bb_contract_pack_status_text, :text
      add :custentity_bb_contract_pack_start_date, :text
      add :custentity_bb_contract_pack_last_mod_dt, :text
      add :custentity_bb_contract_pack_end_date, :text
      add :custentity_bb_contract_pack_dur_num, :text
      add :custentity_bb_contract_pack_comments, :text
      add :custentity_bb_contract_pack_comm_history, :text
      add :custentity_bb_comm_snap_shot_record, :text
      add :custentity_bb_comm_history_notes, :text
      add :custentity_bb_comm_difference_approved, :text
      add :custentity_bb_change_of_scope_reason, :text
      add :custentity_bb_change_of_scope_date, :text
      add :custentity_bb_cancellation_reason, :text
      add :custentity_bb_cancellation_reason_comm, :text
      add :custentity_bb_cancellation_date, :text
      add :custentity_bb_call_ahead_phone, :text
      add :custentity_bb_cac_resigned_date, :text
      add :custentity_bb_cac_deadline_date, :text
      add :custentity_bb_built_year_num, :text
      add :custentity_bb_bom_status_list, :text
      add :custentity_bb_bom_printed_date, :text
      add :custentity_bb_bom_edited, :text
      add :custentity_bb_bodhi_project_id_text, :text
      add :custentity_bb_battery, :text
      add :custentity_bb_battery_quantity, :text
      add :custentity_bb_azimuth_degrees_num, :text
      add :custentity_bb_avg_utilitybill_month_amt, :text
      add :custentity_bb_auth_having_jurisdiction, :text
      add :custentity_bb_aug_kwh_integer, :text
      add :custentity_bb_assessor_parcel_num, :text
      add :custentity_bb_apr_kwh_integer, :text
      add :custentity_bb_alt_phone, :text
      add :custentity_bb_adv_payment_schdl_tot_amt, :text
      add :custentity_bb_adv_payment_schdl_percent, :text
      add :custentity_bb_adv_payment_schdl_count, :text
      add :custentity_bb_actual_equipment_ship_date, :text
      add :custentity_bb_act_wrnty_total_amount, :text
      add :custentity_bb_accrual_je_created_date, :text
      add :custentity_actgrp_8_status, :text
      add :custentity_actgrp_8_start_date, :text
      add :custentity_actgrp_8_last_mod_date, :text
      add :custentity_actgrp_8_end_date, :text
      add :custentity_actgrp_8_duration, :text
      add :custentity_actgrp_8_comments, :text
      add :custentity_actgrp_8_comment_history, :text
      add :custentity_actgrp_5_status, :text
      add :custentity_actgrp_5_start_date, :text
      add :custentity_actgrp_5_last_mod_date, :text
      add :custentity_actgrp_5_end_date, :text
      add :custentity_actgrp_5_duration, :text
      add :custentity_actgrp_5_comments, :text
      add :custentity_actgrp_5_comment_history, :text
      add :custentity_actgrp_136_status, :text
      add :custentity_actgrp_136_start_date, :text
      add :custentity_actgrp_136_last_mod_date, :text
      add :custentity_actgrp_136_end_date, :text
      add :custentity_actgrp_136_duration, :text
      add :custentity_actgrp_136_comments, :text
      add :custentity_actgrp_136_comment_history, :text
      add :custentity_actgrp_133_status, :text
      add :custentity_actgrp_133_start_date, :text
      add :custentity_actgrp_133_last_mod_date, :text
      add :custentity_actgrp_133_end_date, :text
      add :custentity_actgrp_133_duration, :text
      add :custentity_actgrp_133_comments, :text
      add :custentity_actgrp_133_comment_history, :text
      add :custentity_actgrp_119_status, :text
      add :custentity_actgrp_119_start_date, :text
      add :custentity_actgrp_119_last_mod_date, :text
      add :custentity_actgrp_119_end_date, :text
      add :custentity_actgrp_119_duration, :text
      add :custentity_actgrp_119_comments, :text
      add :custentity_actgrp_119_comment_history, :text
      add :custentity_actgrp_11_status, :text
      add :custentity_actgrp_11_start_date, :text
      add :custentity_actgrp_11_last_mod_date, :text
      add :custentity_actgrp_11_end_date, :text
      add :custentity_actgrp_11_duration, :text
      add :custentity_actgrp_11_comments, :text
      add :custentity_actgrp_11_comment_history, :text
      add :custentity_skl_on_hold_comment, :text
      add :custentity_skl_hs_net_revenue, :text
      add :custentity_skl_hs_dealer_fee, :text
      add :custentity_bb_warehouse_location, :text
      add :custentity_skl_auto_created_nma_document, :text
      add :custentity_skl_inverter_size, :text
      add :custentity_skl_sales_adders, :text
      add :custentity_skl_sales_promises, :text

      timestamps()
    end

    create unique_index(:netsuite_projects, [:netsuite_project_id])
  end

  def down do
    drop table("netsuite_projects")
  end
end
